### ISSUE TITLE
Document criteria relevant for orga / repo counting

### ISSUE THREAD

**Issue by MarkusTiede** [digital-sustainability/oss-github-benchmark#14]
It'd be useful knowing the criteria that are relevant for the metrics being gathered from the organizations and repositories: e.g. Baloise is afaict currently listed with 11 repositories though our orga hast ~90 including the archived ones. Thanks for clarifying!

**Comment by maemst** [comment]
Thank you for your comment. @CodeOneTwo or @inthemill, do you see why not all repos of baloise are added on the "Explore" list? In the bubble graph, there are 87 repos listet:
![image](https://user-images.githubusercontent.com/7910243/101622767-c2b17280-3a17-11eb-9c29-2776713976f3.png)

**Comment by CodeOneTwo** [comment]
@MarkusTiede We had a limit on repos, which we removed. The data will be updated soon. I think we should improve the explore tab and link to there
