### ISSUE TITLE
Add Lib4RI to the repo

### ISSUE THREAD

**Issue by mirodietiker** [digital-sustainability/oss-github-benchmark#146]
See their repositories:
https://github.com/orgs/Lib4RI/repositories

I think it's still missing.

While on this, i see that their other clients are not all represented in the repo list:
https://www.dora.lib4ri.ch/

PSI is present, but i'm missing **eawag, Empa and WSL** and i'm pretty sure that all of them have some work published.

**Comment by maemst** [comment]
I added "Lib4RI" as a new community institution. Hope that fits!
https://github.com/digital-sustainability/oss-github-benchmark/commit/a4098ddeea34e23ace25ee1529b0a4beba222cc4
