### ISSUE TITLE
Question : How is your inventory computed?

### ISSUE THREAD

**Issue by ponceta** [digital-sustainability/oss-github-benchmark#155]
I know at least three public OSS swiss organisations which don't appear in your benchmark :

https://github.com/qwat
https://github.com/qgep
https://github.com/teksi (empty yet)

Providing OSS GIS solutions to swiss administrations for public infrastuctures.

What makes an organisation and their repositories appear into your benchmark?

**Comment by maemst** [comment]
This is the list of organisations:
https://github.com/digital-sustainability/oss-github-benchmark/blob/master/data-gathering/github_repos.json
You can add new organizations to the right section as pull request.

**Comment by maemst** [comment]
I added the three orgs as new community instutition "TEKSI, QGEP, QWAT". Hope that fits!
https://github.com/digital-sustainability/oss-github-benchmark/commit/a4098ddeea34e23ace25ee1529b0a4beba222cc4

**Comment by ponceta** [comment]
Thank you! :) Glad to see how rich the OSS sector is in Switzerland!

**Comment by maemst** [comment]
Ah, great, I just saw https://github.com/VilleDePully is missing, too! I'll add it in a minute.

**Comment by ponceta** [comment]
To my knowledge :
https://github.com/sitnyon (SIT Nyon)
https://github.com/yverdon (SIT Yverdon)
https://github.com/asit-asso (ASIT)
https://github.com/sige-riviera (SIGE)
;)

**Comment by maemst** [comment]
Thanks for the links! I added the new institutions: https://github.com/digital-sustainability/oss-github-benchmark/commit/7407522b06fb65f974271aa4a13ebcbb04b09599
