### ISSUE TITLE
Create new list of user profiles and crawl developer-related data from GitHub

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#156]
**Get all affiliated users from a repository**
Important:
- [owner](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.owner)
- [get_collaborators(affiliation=NotSet) ](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_collaborators)
- [get_commits(sha=NotSet, path=NotSet, since=NotSet, until=NotSet, author=NotSet)](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_commits)
- [get_contributors(anon=NotSet)](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_contributors)

Nice-to-have:
- [get_assignees()](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_assignees)
- [get_issues(milestone=NotSet, state=NotSet, assignee=NotSet, mentioned=NotSet, labels=NotSet, sort=NotSet, direction=NotSet, since=NotSet, creator=NotSet)](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_issues)
- [get_stargazers()](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_stargazers)
- [get_subscribers()](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_subscribers)
- [get_watchers()](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_watchers)

API reference for user data on GitHub:
https://pygithub.readthedocs.io/en/latest/github_objects/NamedUser.html
https://docs.github.com/en/rest/reference/users

**Personal data of the person that should be stored:**
- login -> GitHub user name
- name -> name of the person
- avatar_url -> picture or other image of person
- bio -> information about person
- blog -> website of the person
- company -> employer of the person
- email -> email address of the person
- twitter_username -> Twitter user of the person
- location -> place of the person (assuming in Switzerland)
- created_at -> date when person joined GitHub
- updated_at -> date when person updated the GitHub profile

**Statistical data of the person that should be stored:**
- contributions -> number of GitHub contributions of the person (in total or last year?)
- public_repos -> number of GitHub repos of the person
- public_gists -> number of short public GitHub notes of the person
- followers -> number of GitHub followers of the person
- following -> number of GitHub accounts the person is following
- get_orgs() -> get the GitHub organizations the persons is member of
- get_repos() -> get the GitHub repos the person owns

**Comment by hairmare** [comment]
would this be opt-in or opt-out?
