### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by hairmare** [digital-sustainability/oss-github-benchmark#163]
imho this repo should have a `CONTRIBUTING.md` to help realise that using `uuid -v4` is the way to create new uuids and other "get merged asap" requirements.

**Comment by MarkusTiede** [comment]
Good point - at the moment I was searching for information on how to add more organization profiles for an already existing institution see:
- https://github.com/digital-sustainability/open-source/issues/19
