### ISSUE TITLE
Add european broadcasting union

### ISSUE THREAD

**Issue by hairmare** [digital-sustainability/oss-github-benchmark#17]
Would you consider EBU in the scope of this repo? They are headquartered near Geneva and their GitHub is @ebu.

If it's in scope, what categories would it belong into? The `Gov_*` categories seem obvious but I can't find one that would work well for NGOs like EBU.

**Comment by maemst** [comment]
Sure, EBU sounds very interesting. I suggest to create a new sector "NGOs" and then add @ebu there.
