### ISSUE TITLE
Add a script to gather statistics about individual developer of a country

### ISSUE THREAD

**Issue by CodeOneTwo** [digital-sustainability/oss-github-benchmark#21]
Not only OSS organizations of a specific country are interesting.
It would be nice to gather stats about independent developer of a country.
How to gather a list of those (or if it has to be maintained manually) is unclear atm

**Comment by hairmare** [comment]
Repos that belong to an orga would also be something to consider. I'm thinking of things like https://github.com/newscoop/theme-JournalB.

It's clearly an OSS repo that has a strong tie to local Media here in Berne, but it's also very much not part of an orga that is remotely in scope (as far as my understanding of scope goes).

newscoop is a sourceFabric product and apart from them having clients in CH they don't have any special ties to CH.

Does sourceFabric being contracted to make a bespoke OSS theme for their AGPL qualify? The theme isn't just a tiny bit of CSS, it's rather heavy on being a complete solution. I think it even comes with a bespoke font. Maybe @appswithlove can let us know if that is bundled with the theme.

**Comment by hairmare** [comment]
I keep stumbiling over scope defintion issues ad I'll keep abusing this issue to keep track of them until @maemst weighs in ;)

Were would we sort @egamma regarding his VS Code (https://github.com/microsoft/vscode)  effort that was spearheaded by MSFT Zurich? Would this be something we would want him and/or msft-ch to weigh in on?

The "looking at indivual repos" thing sure does pose some challenges in comparison to the "generalize on the orga level" approach.

**Comment by RockstaYT** [comment]
Openproject Workpackage #6961
