### ISSUE TITLE
Change icons of Institution and Repository Ranking in the top menu and favicon

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#224]
![image](https://user-images.githubusercontent.com/7910243/181732702-ee208081-1f55-49ac-96fb-d0d8fb7a9aeb.png)

New icon for "Institution Ranking": https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aapartment%3AFILL%400%3Bwght%40600%3BGRAD%400%3Bopsz%4040
![apartment_FILL0_wght600_GRAD0_opsz40](https://user-images.githubusercontent.com/7910243/181733765-02d05033-1346-482e-bd5d-4e8937793292.png)

New icon for "Repository Ranking": https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Agrid_view%3AFILL%400%3Bwght%40600%3BGRAD%400%3Bopsz%4040
![grid_view_FILL0_wght600_GRAD0_opsz40](https://user-images.githubusercontent.com/7910243/181734823-54b65d4f-6ebb-468b-9b1c-834102fcfeb6.png)

New favicon for OSS Benchmark website: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aview_in_ar%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4040
![view_in_ar_FILL0_wght400_GRAD0_opsz40](https://user-images.githubusercontent.com/7910243/181734559-85c878e2-5ed1-43ed-bb68-026281116132.png)

**Comment by wal1Luana** [comment]
wurde erledigt
