### ISSUE TITLE
Some Institutions are not crawled

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#301]
The following Institution is not crawled although the org on GitHub still exists:

https://ossbenchmark.com/institutions/sp
https://github.com/spschweiz

![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/7910243/422a4d1c-3241-4d01-a782-b5ecd672f6af)

**Comment by RockstaYT** [comment]
https://github.com/spschweiz is not an institution. Because of that the orgs api doesnt find it @maemst
