### ISSUE TITLE
Numbers not displayed in Institution overview

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#304]
The following numbers are not displayed:
https://ossbenchmark.com/institutions/camptocamp
![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/7910243/a15969a4-1261-4752-945b-60f76e0d0b26)

**Comment by RockstaYT** [comment]
Linked variables were Updated.

PRs and Issues should be updated with the new deployment sometime in this week.

see: https://github.com/digital-sustainability/oss-github-benchmark/issues/306

**Comment by maemst** [comment]
Problem solved!
