### ISSUE TITLE
Sorting in Repository Ranking does not work properly

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#305]
Sorting for Issues and Pull Requests does not work:
https://ossbenchmark.com/repositories
![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/7910243/58c50d1b-fecb-41e2-891a-f6c23841ecd2)

**Comment by Alexandre-DSL** [comment]
Data for PRs and Issues is now populated and sorting is working:
![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/166725941/fb03735d-ede1-47e8-9bac-ab20b26904e8)
