### ISSUE TITLE
Not all data is displayed in Repos detail view

### ISSUE THREAD

**Issue by maemst** [digital-sustainability/oss-github-benchmark#306]
The followind data (red boxes) is missing in the Repos detail views:
https://ossbenchmark.com/repositories/liip/LiipImagineBundle
![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/7910243/1156fc49-8f73-401a-940c-5bb1a98af031)

**Comment by RockstaYT** [comment]
Everything besides Issues and PR is resolved.

Issues and PR Data will be Updated with the upcoming crawling runs, data was handled incorrectly.

**Comment by Alexandre-DSL** [comment]
Data related to Issues and PRs is now properly populated:
![image](https://github.com/digital-sustainability/oss-github-benchmark/assets/166725941/4a17f717-9810-4498-a16a-655221bc4d1e)


Closing this issue.
