### ISSUE TITLE
rename sector Banking to BankingAndFinance

### ISSUE THREAD

**Issue by hairmare** [digital-sustainability/oss-github-benchmark#31]
I'm creating this issue since I see the following cases that to not fit the "Banking" umbrella but whould make sense lumping together.

* providers like Datatrans from: #30 
* digital currency companies (ie. blockchain based stuff)
* service provider specific to the sector (ie. finnova if they had a GitHub)
* fiduciary companies (Treuhänder)

I'm guessing the sector "Banking" isn't intended for just only what FINMA would strictly classify as a Bank so it might  make sense to redefine it. I'm not sure where I would cut the line though since the last three examples could fit elsewhere just as well.

**Comment by CodeOneTwo** [comment]
Makes sense. What name would you suggest @maemst
