### ISSUE TITLE
Fix Data Fetching Build

### ISSUE THREAD

**Issue by CodeOneTwo** [digital-sustainability/oss-github-benchmark#66]
Currently the data fetching with github actions doesn't work, because there is a time limit (360m) for a build. Increasing doesn't work because github only allows to change it for self hosted github runners.
I run the build locally and it results in a file >300mb

**Comment by titfortat265358** [comment]
I fixed it:
The progress of fetching gets temporary saved now and I changed the GH action so it runs three times per day.
